# Generated by Django 3.2.9 on 2021-11-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=70)),
                ('birth_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('international_passport', models.CharField(max_length=8)),
                ('vaccine', models.CharField(max_length=70)),
            ],
        ),
    ]
