# Generated by Django 3.2.9 on 2021-11-10 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='vaccine',
        ),
    ]
